### PR TITLE
Add kokoro build files

### PR DESCRIPTION
**Pull request by dj2**
This CL adds build files for the various Kokoro bots. The running of
ctest is disabled as it does not pass currently.

Issue #2

### CODE REVIEW

**Comment by dj2** [comment]
@ehsannas ptal.

**Review by ehsannas — COMMENTED** [review]
There are a number of `ctest` commands that are commented out. Is that intentional?

**Comment by dj2** [comment]
Yes, I'm working on making ctest pass, but wanted to get at least the build part up and running first.

**Review by ehsannas — APPROVED** [review]
LGTM

**Pull request merged**
